name: Audit2Deny

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Safely-deploy-assignment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # Log into Azure
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 
      
      - name: Deploy assignment to Ring 0 regions
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.AZURE_RG }}
          parameters: SDPRegions=${{ vars.RING0REGIONS}} effect=Deny
          template: policyassignment.json
    
      run: sleep 10s
    
      - name: Deploy assignment to Ring 1 regions
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.AZURE_RG }}
          parameters: SDPRegions=${{ vars.RING1REGIONS}} effect=Deny
          template: policyassignment.json
      
      run: sleep 10s
     
      - name: Deploy assignment to Ring 2 regions
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.AZURE_RG }}
          parameters: SDPRegions=${{ vars.RING2REGIONS}} effect=Deny
          template: policyassignment.json

      run: sleep 10s
      
      - name: Deploy assignment to ROW regions
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.AZURE_RG }}
          parameters: SDPRegions=${{ vars.ROWREGIONS}} effect=Deny
          template: policyassignment.json
